Assignment 6 — Build a Complete ML Pipeline
Objective
Create a production-style ML pipeline.
Dataset
Participants must choose dataset with mixed features.
Example:
• car price prediction
• insurance charges dataset
Tasks
Build pipeline including:
1. Data loading
2. Data cleaning
3. Feature engineering
4. Train-test split
5. Model training
6. Hyperparameter tuning
7. Model evaluation
8. Save model using joblib
Expected Output
Participants must deliver:
• Python script / notebook
• trained model
• evaluation report

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import joblib

In [5]:
df = pd.read_csv("CarPrice.csv")

print(df.head())
print(df.info())

   Unnamed: 0     name  year  selling_price  km_driven    fuel seller_type  \
0           0   Maruti  2014         450000     145500  Diesel  Individual
1           2  Hyundai  2010         225000     127000  Diesel  Individual
2           4  Hyundai  2017         440000      45000  Petrol  Individual
3           7   Toyota  2011         350000      90000  Diesel  Individual
4           8     Ford  2013         200000     169000  Diesel  Individual

  transmission        owner  seats  max_power (in bph) Mileage Unit  Mileage  \
0       Manual  First Owner      5               74.00         kmpl    23.40
1       Manual  First Owner      5               90.00         kmpl    23.00
2       Manual  First Owner      5               81.86         kmpl    20.14
3       Manual  First Owner      5               67.10         kmpl    23.59
4       Manual  First Owner      5               68.10         kmpl    20.00

   Engine (CC)
0         1248
1         1396
2         1197
3         1364
4         1399
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2095 entries, 0 to 2094
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          2095 non-null   int64
 1   name                2095 non-null   object
 2   year                2095 non-null   int64
 3   selling_price       2095 non-null   int64
 4   km_driven           2095 non-null   int64
 5   fuel                2095 non-null   object
 6   seller_type         2095 non-null   object
 7   transmission        2095 non-null   object
 8   owner               2095 non-null   object
 9   seats               2095 non-null   int64
 10  max_power (in bph)  2095 non-null   float64
 11  Mileage Unit        2095 non-null   object
 12  Mileage             2095 non-null   float64
 13  Engine (CC)         2095 non-null   int64
dtypes: float64(2), int64(6), object(6)
memory usage: 229.3+ KB
None

In [6]:
df.shape

(2095, 14)

Step 2: Data Cleaning

Data cleaning is important to ensure that the dataset does not contain:

• Missing values
• Duplicate rows
• Unnecessary columns

In [7]:
# remove unnecessary column
df.drop("Unnamed: 0", axis=1, inplace=True)

df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,seats,max_power (in bph),Mileage Unit,Mileage,Engine (CC)
0,Maruti,2014,450000,145500,Diesel,Individual,Manual,First Owner,5,74.00,kmpl,23.40,1248
1,Hyundai,2010,225000,127000,Diesel,Individual,Manual,First Owner,5,90.00,kmpl,23.00,1396
2,Hyundai,2017,440000,45000,Petrol,Individual,Manual,First Owner,5,81.86,kmpl,20.14,1197
3,Toyota,2011,350000,90000,Diesel,Individual,Manual,First Owner,5,67.10,kmpl,23.59,1364
4,Ford,2013,200000,169000,Diesel,Individual,Manual,First Owner,5,68.10,kmpl,20.00,1399

In [8]:
df.isnull().sum()

name                  0
year                  0
selling_price         0
km_driven             0
fuel                  0
seller_type           0
transmission          0
owner                 0
seats                 0
max_power (in bph)    0
Mileage Unit          0
Mileage               0
Engine (CC)           0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

## Step 3: Feature Engineering
Feature engineering prepares the dataset for machine learning.
Steps:
1. Separate features and target variable
2. Convert categorical variables into numerical form
3. Encode categorical variables using One-Hot Encoding

In [10]:
X = df.drop("selling_price", axis=1)
y = df["selling_price"]

In [11]:
X.select_dtypes(include="object").columns

Index(['name', 'fuel', 'seller_type', 'transmission', 'owner', 'Mileage Unit'], dtype='object')

In [12]:
X = pd.get_dummies(X, drop_first=True)

X.head()

,year,km_driven,seats,max_power (in bph),Mileage,Engine (CC),name_Ford,name_Honda,name_Hyundai,name_Mahindra,...,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,Mileage Unit_kmpl
0,2014,145500,5,74.00,23.40,1248,False,False,False,False,...,False,False,True,False,True,False,False,False,False,True
1,2010,127000,5,90.00,23.00,1396,False,False,True,False,...,False,False,True,False,True,False,False,False,False,True
2,2017,45000,5,81.86,20.14,1197,False,False,True,False,...,False,True,True,False,True,False,False,False,False,True
3,2011,90000,5,67.10,23.59,1364,False,False,False,False,...,False,False,True,False,True,False,False,False,False,True
4,2013,169000,5,68.10,20.00,1399,True,False,False,False,...,False,False,True,False,True,False,False,False,False,True

In [13]:

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("Training shape:", X_train.shape)
print("Testing shape:", X_test.shape)

Training shape: (1676, 26)
Testing shape: (419, 26)

In [14]:

model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

## Step 6: Hyperparameter Tuning

We use GridSearchCV to find the best alpha parameter for Ridge Regression.

In [15]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

ridge = Ridge()

param_grid = {
    "alpha": [0.01, 0.1, 1, 10, 100]
}

grid = GridSearchCV(ridge, param_grid, cv=5)

grid.fit(X_train, y_train)

best_model = grid.best_estimator_

print("Best Parameters:", grid.best_params_)

Best Parameters: {'alpha': 0.1}

## Step 7: Model Evaluation

We evaluate the model using the following metrics:

• MAE (Mean Absolute Error)
• RMSE (Root Mean Squared Error)
• R² Score

In [16]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

y_pred = best_model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 75842.64542505359
RMSE: 99088.43787183914
R2 Score: 0.7922885037372394

In [18]:
import joblib

joblib.dump(best_model, "car_price_model.joblib")

print("Model saved successfully")

Model saved successfully

Evaluation Report

You must include the model performance results.

Your results:

Metric	Value
MAE	75,842
RMSE	99,088
R² Score	0.79
Write this in your report:

Model Evaluation Results

The Ridge Regression model was evaluated using three performance metrics.

MAE (Mean Absolute Error)
= 75,842
This means the model prediction differs from the actual car price by approximately ₹75,842 on average.

RMSE (Root Mean Squared Error)
= 99,088
This metric penalizes larger prediction errors more strongly.

R² Score
= 0.79
This indicates that the model explains 79% of the variation in car selling prices, which shows good predictive performance.